### ISSUE TITLE
Feature 10: User can login to their account

### ISSUE THREAD

**Issue by raymondkhoaho** [raymondkhoaho/InstaPet#10]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can login to their account

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
Clicking log in brings user to explore home page

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-12-30 at 11 27 48 AM](https://user-images.githubusercontent.com/113560956/210105779-5583dee4-0654-482e-8b97-836dc7db3b24.png)
![Screen Shot 2022-12-30 at 11 28 01 AM](https://user-images.githubusercontent.com/113560956/210105787-5bfbf823-5ba5-46fb-996e-b59a34272585.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to have POST request for sign-in
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component for sign-in
- [x] Update navbar component to update user profile icon

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
