### ISSUE TITLE
Feature 11: User can sign out of their account

### ISSUE THREAD

**Issue by raymondkhoaho** [raymondkhoaho/InstaPet#11]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sign out of their account

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
Clicking Sign Out brings user back to login page

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-12-30 at 11 29 34 AM](https://user-images.githubusercontent.com/113560956/210105886-f3a2d77d-548f-466d-82b8-787be500556e.png)
![Screen Shot 2022-12-30 at 11 29 25 AM](https://user-images.githubusercontent.com/113560956/210105891-f7de3c5d-bf86-4433-aed1-a48491b778ac.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Create a component for a sign out button
- [x] Add handleSignOut function for sign out button to remove token from local storage

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
