### ISSUE TITLE
Feature 9: User can sign up for an account

### ISSUE THREAD

**Issue by raymondkhoaho** [raymondkhoaho/InstaPet#9]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sign up for an account

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
Initial screen will be sign up modal.
Clicking on sign up brings user to log in page

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-12-30 at 11 26 44 AM](https://user-images.githubusercontent.com/113560956/210105698-1a65fabe-b6b7-431d-ad5c-44b9033a28db.png)
![Screen Shot 2022-12-30 at 11 26 36 AM](https://user-images.githubusercontent.com/113560956/210105700-e6ff2ca0-ef38-415b-91ef-19b594af9f3c.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to include POST request to add new users
- [x] Make sure all required parameters are inserted into database table
- [x] Add argon2 for hashing password
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component for a sign up form
- [x] Make sure that there's an on submit handler once you click sign up button
- [x] Make sure the on submit catches any empty required fields
- [x] If a field is missing, have a error alert come up showing error
- [x] If sign up is successful, have a success alert come up showing success
- [x] If successful, switch from sign up form to sign in form

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
